# ETAPA 1 - build
FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN cd demo && mvn clean package -DskipTests

# ETAPA 2 - run
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/demo/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]